# https://cirrus-ci.org/guide/tips-and-tricks/#sharing-configuration-between-tasks
freebsd_versions: &FREEBSD_VERSIONS
  env:
    FREEBSD_LEGACY:     freebsd-13-5
    FREEBSD_PRODUCTION: freebsd-14-2
    FREEBSD_CURRENT:    freebsd-15-0-snap

freebsd_template: &FREEBSD_ENV
  environment:
    APPEND_LIB: /usr/local/lib
    APPEND_INCLUDES: /usr/local/include
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_LOG_TIMESTAMP: true

freebsd_template_latest: &FREEBSD_ENV_PRODUCTION
  << : *FREEBSD_VERSIONS
  freebsd_instance:
    image_family: $FREEBSD_PRODUCTION
  << : *FREEBSD_ENV

freebsd_configure_artifacts: &FREEBSD_CONFIGURE_ARTIFACTS
  always:
    rename_script:
      - cp xen/.config xen-config
    config_artifacts:
      path: xen-config
      type: text/plain

task:
  name: 'FreeBSD: full build'

  # It's not possible to use the matrix keyword in YAML aliases, as they
  # keyword usage is restricted to task, docker_builder or pipe.  Attempting to
  # use a YAML alias with the duplicated keys doesn't work either. Use an env
  # variable so the version can also be appended to the task alias.
  << : *FREEBSD_VERSIONS
  env:
    matrix:
      FREEBSD_VERSION: $FREEBSD_LEGACY
      FREEBSD_VERSION: $FREEBSD_PRODUCTION
      FREEBSD_VERSION: $FREEBSD_CURRENT

  alias: freebsd_full_$FREEBSD_VERSION
  freebsd_instance:
    image_family: $FREEBSD_VERSION

  << : *FREEBSD_ENV

  install_script: pkg install -y seabios gmake ninja bash
                                 pkgconf bison perl5
                                 yajl lzo2 pixman argp-standalone
                                 libxml2 glib git python3

  configure_script:
    - cc --version
    - ./configure --with-system-seabios=/usr/local/share/seabios/bios.bin
    - gmake -j`sysctl -n hw.ncpu` -C xen clang=y defconfig

  << : *FREEBSD_CONFIGURE_ARTIFACTS

  build_script:
    - gmake -j`sysctl -n hw.ncpu` clang=y

task:
  name: 'FreeBSD: randconfig build'

  # It's not possible to use the matrix keyword in YAML aliases, as they
  # keyword usage is restricted to task, docker_builder or pipe.  Attempting to
  # use a YAML alias with the duplicated `image_family` keys doesn't work
  # either. Abstract the version numbers at least.
  << : *FREEBSD_VERSIONS
  freebsd_instance:
    matrix:
      image_family: $FREEBSD_LEGACY
      image_family: $FREEBSD_PRODUCTION
      image_family: $FREEBSD_CURRENT

  << : *FREEBSD_ENV

  install_script: pkg install -y gmake python3 bison

  configure_script:
    - cc --version
    - gmake -j`sysctl -n hw.ncpu` -C xen clang=y \
            KCONFIG_ALLCONFIG=tools/kconfig/allrandom.config randconfig

  << : *FREEBSD_CONFIGURE_ARTIFACTS

  build_script:
    - gmake -j`sysctl -n hw.ncpu` build-xen clang=y

task:
  name: 'FreeBSD: XTF build'
  alias: xtf

  << : *FREEBSD_ENV_PRODUCTION

  clone_script:
    - pkg install -y git
    - git clone --depth 1 https://xenbits.xen.org/git-http/xtf.git

  install_script: pkg install -y gmake

  build_script:
    - cd xtf
    - cc --version
    - git rev-parse HEAD
    - gmake -j`sysctl -n hw.ncpu` LLVM=y
